export const e11 = [
  {
    name: 'pl. de les Tereses',
    dayTypes: [
      {
        dayTypeName: 'weekday',
        hours: [
          { hour: 6, minute: 5 },
          { hour: 6, minute: 25 },
          { hour: 6, minute: 35 },
          { hour: 6, minute: 50 },
          { hour: 7, minute: 0 },
          { hour: 7, minute: 5 },
          { hour: 7, minute: 15 },
          { hour: 7, minute: 25 },
          { hour: 7, minute: 35 },
          { hour: 7, minute: 40 },
          { hour: 7, minute: 50 },
          { hour: 8, minute: 0 },
          { hour: 8, minute: 5 },
          { hour: 8, minute: 15 },
          { hour: 8, minute: 20 },
          { hour: 8, minute: 45 },
          { hour: 9, minute: 15 },
          { hour: 9, minute: 45 },
          { hour: 10, minute: 15 },
          { hour: 10, minute: 45 },
          { hour: 11, minute: 15 },
          { hour: 11, minute: 45 },
          { hour: 12, minute: 15 },
          { hour: 12, minute: 45 },
          { hour: 13, minute: 10 },
          { hour: 13, minute: 15 },
          { hour: 13, minute: 30 },
          { hour: 13, minute: 45 },
          { hour: 14, minute: 0 },
          { hour: 14, minute: 15 },
          { hour: 14, minute: 20 },
          { hour: 14, minute: 40 },
          { hour: 14, minute: 45 },
          { hour: 15, minute: 15 },
          { hour: 15, minute: 30 },
          { hour: 15, minute: 45 },
          { hour: 15, minute: 55 },
          { hour: 16, minute: 15 },
          { hour: 16, minute: 30 },
          { hour: 16, minute: 45 },
          { hour: 17, minute: 0 },
          { hour: 17, minute: 15 },
          { hour: 17, minute: 30 },
          { hour: 17, minute: 45 },
          { hour: 18, minute: 0 },
          { hour: 18, minute: 15 },
          { hour: 18, minute: 30 },
          { hour: 18, minute: 45 },
          { hour: 19, minute: 0 },
          { hour: 19, minute: 15 },
          { hour: 19, minute: 30 },
          { hour: 19, minute: 45 },
          { hour: 20, minute: 15 },
          { hour: 20, minute: 45 },
          { hour: 21, minute: 15 },
          { hour: 21, minute: 45 }
        ]
      },
      {
        dayTypeName: 'weekend',
        hours: [
          { hour: 8, minute: 0 },
          { hour: 9, minute: 0 },
          { hour: 10, minute: 0 },
          { hour: 11, minute: 0 },
          { hour: 12, minute: 0 },
          { hour: 13, minute: 0 },
          { hour: 15, minute: 0 },
          { hour: 16, minute: 0 },
          { hour: 17, minute: 0 },
          { hour: 18, minute: 0 },
          { hour: 19, minute: 0 },
          { hour: 20, minute: 0 },
          { hour: 21, minute: 0 },
          { hour: 22, minute: 0 }
        ]
      }
    ]
  },
  {
    name: 'pl. de Tetuan',
    dayTypes: [
      {
        dayTypeName: 'weekday',
        hours: [
          { hour: 6, minute: 50 },
          { hour: 7, minute: 10 },
          { hour: 7, minute: 20 },
          { hour: 7, minute: 35 },
          { hour: 7, minute: 45 },
          { hour: 7, minute: 50 },
          { hour: 8, minute: 0 },
          { hour: 8, minute: 10 },
          { hour: 8, minute: 20 },
          { hour: 8, minute: 25 },
          { hour: 8, minute: 35 },
          { hour: 8, minute: 45 },
          { hour: 8, minute: 50 },
          { hour: 9, minute: 0 },
          { hour: 9, minute: 5 },
          { hour: 9, minute: 30 },
          { hour: 10, minute: 0 },
          { hour: 10, minute: 30 },
          { hour: 11, minute: 0 },
          { hour: 11, minute: 30 },
          { hour: 12, minute: 0 },
          { hour: 12, minute: 30 },
          { hour: 13, minute: 0 },
          { hour: 13, minute: 30 },
          { hour: 13, minute: 55 },
          { hour: 14, minute: 0 },
          { hour: 14, minute: 15 },
          { hour: 14, minute: 30 },
          { hour: 14, minute: 45 },
          { hour: 15, minute: 0 },
          { hour: 15, minute: 5 },
          { hour: 15, minute: 25 },
          { hour: 15, minute: 30 },
          { hour: 16, minute: 0 },
          { hour: 16, minute: 15 },
          { hour: 16, minute: 30 },
          { hour: 16, minute: 40 },
          { hour: 17, minute: 0 },
          { hour: 17, minute: 15 },
          { hour: 17, minute: 30 },
          { hour: 17, minute: 45 },
          { hour: 18, minute: 0 },
          { hour: 18, minute: 15 },
          { hour: 18, minute: 30 },
          { hour: 18, minute: 45 },
          { hour: 19, minute: 0 },
          { hour: 19, minute: 15 },
          { hour: 19, minute: 30 },
          { hour: 19, minute: 45 },
          { hour: 20, minute: 0 },
          { hour: 20, minute: 15 },
          { hour: 20, minute: 30 },
          { hour: 21, minute: 0 },
          { hour: 21, minute: 30 },
          { hour: 22, minute: 0 },
          { hour: 22, minute: 30 }
        ]
      },
      {
        dayTypeName: 'weekend',
        hours: [
          { hour: 8, minute: 49 },
          { hour: 9, minute: 49 },
          { hour: 10, minute: 49 },
          { hour: 11, minute: 49 },
          { hour: 12, minute: 49 },
          { hour: 13, minute: 49 },
          { hour: 15, minute: 49 },
          { hour: 16, minute: 49 },
          { hour: 17, minute: 49 },
          { hour: 18, minute: 49 },
          { hour: 19, minute: 49 },
          { hour: 20, minute: 49 },
          { hour: 21, minute: 49 },
          { hour: 22, minute: 49 }
        ]
      }
    ]
  },
  {
    name: 'rda. Universitat, 21',
    dayTypes: [
      {
        dayTypeName: 'weekday',
        hours: [
          { hour: 6, minute: 55 },
          { hour: 7, minute: 15 },
          { hour: 7, minute: 25 },
          { hour: 7, minute: 40 },
          { hour: 7, minute: 50 },
          { hour: 7, minute: 55 },
          { hour: 8, minute: 5 },
          { hour: 8, minute: 15 },
          { hour: 8, minute: 25 },
          { hour: 8, minute: 30 },
          { hour: 8, minute: 40 },
          { hour: 8, minute: 50 },
          { hour: 8, minute: 55 },
          { hour: 9, minute: 5 },
          { hour: 9, minute: 10 },
          { hour: 9, minute: 35 },
          { hour: 10, minute: 5 },
          { hour: 10, minute: 35 },
          { hour: 11, minute: 5 },
          { hour: 11, minute: 35 },
          { hour: 12, minute: 5 },
          { hour: 12, minute: 35 },
          { hour: 13, minute: 5 },
          { hour: 13, minute: 35 },
          { hour: 14, minute: 0 },
          { hour: 14, minute: 5 },
          { hour: 14, minute: 20 },
          { hour: 14, minute: 35 },
          { hour: 14, minute: 50 },
          { hour: 15, minute: 5 },
          { hour: 15, minute: 10 },
          { hour: 15, minute: 30 },
          { hour: 15, minute: 35 },
          { hour: 16, minute: 5 },
          { hour: 16, minute: 20 },
          { hour: 16, minute: 35 },
          { hour: 16, minute: 45 },
          { hour: 17, minute: 5 },
          { hour: 17, minute: 20 },
          { hour: 17, minute: 35 },
          { hour: 17, minute: 50 },
          { hour: 18, minute: 5 },
          { hour: 18, minute: 20 },
          { hour: 18, minute: 35 },
          { hour: 18, minute: 50 },
          { hour: 19, minute: 5 },
          { hour: 19, minute: 20 },
          { hour: 19, minute: 35 },
          { hour: 19, minute: 50 },
          { hour: 20, minute: 5 },
          { hour: 20, minute: 20 },
          { hour: 20, minute: 35 },
          { hour: 21, minute: 5 },
          { hour: 21, minute: 35 },
          { hour: 22, minute: 5 },
          { hour: 22, minute: 35 }
        ]
      },
      {
        dayTypeName: 'weekend',
        hours: [
          { hour: 8, minute: 55 },
          { hour: 9, minute: 55 },
          { hour: 10, minute: 55 },
          { hour: 11, minute: 55 },
          { hour: 12, minute: 55 },
          { hour: 13, minute: 55 },
          { hour: 15, minute: 55 },
          { hour: 16, minute: 55 },
          { hour: 17, minute: 55 },
          { hour: 18, minute: 55 },
          { hour: 19, minute: 55 },
          { hour: 20, minute: 55 },
          { hour: 21, minute: 55 },
          { hour: 22, minute: 55 }
        ]
      }
    ]
  }
]

export const firstStop = [
  { hour: 6, minute: 5 },
  { hour: 6, minute: 25 },
  { hour: 6, minute: 35 },
  { hour: 6, minute: 50 },
  { hour: 7, minute: 0 },
  { hour: 7, minute: 5 },
  { hour: 7, minute: 15 },
  { hour: 7, minute: 25 },
  { hour: 7, minute: 35 },
  { hour: 7, minute: 40 },
  { hour: 7, minute: 50 },
  { hour: 8, minute: 0 },
  { hour: 8, minute: 5 },
  { hour: 8, minute: 15 },
  { hour: 8, minute: 20 },
  { hour: 8, minute: 45 },
  { hour: 9, minute: 15 },
  { hour: 9, minute: 45 },
  { hour: 10, minute: 15 },
  { hour: 10, minute: 45 },
  { hour: 11, minute: 15 },
  { hour: 11, minute: 45 },
  { hour: 12, minute: 15 },
  { hour: 12, minute: 45 },
  { hour: 13, minute: 10 },
  { hour: 13, minute: 15 },
  { hour: 13, minute: 30 },
  { hour: 13, minute: 45 },
  { hour: 14, minute: 0 },
  { hour: 14, minute: 15 },
  { hour: 14, minute: 20 },
  { hour: 14, minute: 40 },
  { hour: 14, minute: 45 },
  { hour: 15, minute: 15 },
  { hour: 15, minute: 30 },
  { hour: 15, minute: 45 },
  { hour: 15, minute: 55 },
  { hour: 16, minute: 15 },
  { hour: 16, minute: 30 },
  { hour: 16, minute: 45 },
  { hour: 17, minute: 0 },
  { hour: 17, minute: 15 },
  { hour: 17, minute: 30 },
  { hour: 17, minute: 45 },
  { hour: 18, minute: 0 },
  { hour: 18, minute: 15 },
  { hour: 18, minute: 30 },
  { hour: 18, minute: 45 },
  { hour: 19, minute: 0 },
  { hour: 19, minute: 15 },
  { hour: 19, minute: 30 },
  { hour: 19, minute: 45 },
  { hour: 20, minute: 15 },
  { hour: 20, minute: 45 },
  { hour: 21, minute: 15 },
  { hour: 21, minute: 45 }
]

export const secondStop = [
  { hour: 6, minute: 55 },
  { hour: 7, minute: 15 },
  { hour: 7, minute: 25 },
  { hour: 7, minute: 40 },
  { hour: 7, minute: 50 },
  { hour: 7, minute: 55 },
  { hour: 8, minute: 5 },
  { hour: 8, minute: 15 },
  { hour: 8, minute: 25 },
  { hour: 8, minute: 30 },
  { hour: 8, minute: 40 },
  { hour: 8, minute: 50 },
  { hour: 8, minute: 55 },
  { hour: 9, minute: 5 },
  { hour: 9, minute: 10 },
  { hour: 9, minute: 35 },
  { hour: 10, minute: 5 },
  { hour: 10, minute: 35 },
  { hour: 11, minute: 5 },
  { hour: 11, minute: 35 },
  { hour: 12, minute: 5 },
  { hour: 12, minute: 35 },
  { hour: 13, minute: 5 },
  { hour: 13, minute: 35 },
  { hour: 14, minute: 0 },
  { hour: 14, minute: 5 },
  { hour: 14, minute: 20 },
  { hour: 14, minute: 35 },
  { hour: 14, minute: 50 },
  { hour: 15, minute: 5 },
  { hour: 15, minute: 10 },
  { hour: 15, minute: 30 },
  { hour: 15, minute: 35 },
  { hour: 16, minute: 5 },
  { hour: 16, minute: 20 },
  { hour: 16, minute: 35 },
  { hour: 16, minute: 45 },
  { hour: 17, minute: 5 },
  { hour: 17, minute: 20 },
  { hour: 17, minute: 35 },
  { hour: 17, minute: 50 },
  { hour: 18, minute: 5 },
  { hour: 18, minute: 20 },
  { hour: 18, minute: 35 },
  { hour: 18, minute: 50 },
  { hour: 19, minute: 5 },
  { hour: 19, minute: 20 },
  { hour: 19, minute: 35 },
  { hour: 19, minute: 50 },
  { hour: 20, minute: 5 },
  { hour: 20, minute: 20 },
  { hour: 20, minute: 35 },
  { hour: 21, minute: 5 },
  { hour: 21, minute: 35 },
  { hour: 22, minute: 5 },
  { hour: 22, minute: 35 }
]
